trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Starting CI Pipeline"
  displayName: 'Start Message'

- script: |
    echo "Build running on:"
    uname -a
  displayName: 'Display Agent Information'

- script: |
    mkdir output
    echo "AZ-400 CI Practice" > output/build.txt
  displayName: 'Generate Build Output'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'output'
    ArtifactName: 'drop'
    publishLocation: 'Container'